#!/usr/bin/env python3

import sys
import utils
from bin import RecycleBin


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Wrong usage.')
        sys.exit(0)

    recycle_bin = RecycleBin(utils.get_bin_directory())

    for filename in sys.argv[1:]:
        created_version = recycle_bin.delete(filename)
        print('File %s was deleted and version %d was created' % (filename, created_version))
