#!/usr/bin/env python

import sys
import utils
from bin import RecycleBin

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Wrong usage.')
        sys.exit(0)

    recycle_bin = RecycleBin(utils.get_bin_directory())
    recycle_bin.remove(sys.argv[1])
